site_name: PyChildren Guidebook

pages:
    - Home: index.md
    - Lessons: 
      - Lesson 1: lesson1.md
      - Lesson 2: lesson02.md
      - Lesson 3: lesson03.md
      - Lesson 4: lesson04.md
      - Lesson 5: lesson05.md
      - Answers: answers.md